# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBook', '0002_auto_20181015_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
